name: CI Pipeline

on:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This ensures all history and tags are fetched

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: myapp:test

    - name: Run tests in Docker container
      run: |
        docker run --rm myapp:test poetry run pytest tests/test_all.py

    - name: List directory contents (for debugging)
      run: |
        docker run --rm myapp:test ls -R